const PROGRAM = {
  workouts: [
    {
      id: 'workout1',
      name: 'Workout 1',
      day: 'Wednesday',
      exercises: [
        {
          id: 'warmup_bike',
          name: 'Stationary Bike Warmup',
          videoUrl: '',
          metric: 'time_only',
          targetTime: 300,
          targetSets: [1, 1, 1, 1, 1],
        },
        {
          id: 'trapbar_deadlift',
          name: 'Trapbar Deadlifts',
          videoUrl: 'https://www.youtube.com/watch?v=VNgxEhOoOjo',
          metric: 'weight_reps',
          targetReps: '8–12',
          targetSets: [2, 3, 3, 3, 1],
        },
        {
          id: 'reverse_lunges',
          name: 'Reverse Lunges w/ Dumbbells',
          videoUrl: 'https://www.youtube.com/watch?v=Q59ZvPhpySM',
          metric: 'weight_reps',
          targetReps: '8–12',
          targetSets: [2, 3, 3, 3, 1],
        },
        {
          id: 'single_leg_rdl',
          name: 'Single Leg Romanian Deadlifts',
          videoUrl: 'https://www.youtube.com/watch?v=ViVhUZGk6i4',
          metric: 'weight_reps',
          targetReps: '6–10',
          targetSets: [2, 3, 3, 3, 1],
        },
        {
          id: 'ytwl',
          name: 'Y, T, W, L — Physioball w/ Dumbbell',
          videoUrl: 'https://www.youtube.com/watch?v=royA3Abyebs&t=12s',
          metric: 'weight_reps',
          targetReps: '4–8',
          targetSets: [2, 3, 3, 3, 1],
        },
        {
          id: 'farmers_carry',
          name: "Farmer's Carry",
          videoUrl: 'https://www.youtube.com/watch?v=Fkzk_RqlYig',
          metric: 'weight_time',
          targetTime: 60,
          targetSets: [2, 3, 3, 3, 1],
        },
        {
          id: 'plank_front',
          name: 'Plank Front',
          videoUrl: 'https://www.youtube.com/watch?v=BvwY-jCPtZE',
          metric: 'time_only',
          targetTimeByWeek: [60, 60, 75, 90, 60],
          targetSets: [2, 3, 3, 3, 1],
        },
        {
          id: 'side_plank_abduction',
          name: 'Side Plank with Hip Abduction',
          videoUrl: 'https://www.youtube.com/watch?v=H2dR3hXdH38',
          metric: 'time_reps',
          targetTime: 30,
          targetReps: '5–10',
          targetSets: [2, 3, 3, 3, 1],
        },
      ],
    },
    {
      id: 'workout2',
      name: 'Workout 2',
      day: 'Friday',
      exercises: [
        {
          id: 'warmup_bike',
          name: 'Stationary Bike Warmup',
          videoUrl: '',
          metric: 'time_only',
          targetTime: 300,
          targetSets: [1, 1, 1, 1, 1],
        },
        {
          id: 'back_squat',
          name: 'Back Squat',
          videoUrl: 'https://www.youtube.com/watch?v=bEv6CCg2BC8',
          metric: 'weight_reps',
          targetReps: '8–12',
          targetSets: [2, 3, 3, 3, 1],
        },
        {
          id: 'single_leg_leg_press',
          name: 'Single Leg Horizontal Leg Press',
          videoUrl: 'https://www.youtube.com/watch?v=QQEW__B5y9I',
          metric: 'weight_reps',
          targetReps: '8–12',
          targetSets: [2, 3, 3, 3, 1],
        },
        {
          id: 'seated_leg_curl',
          name: 'Seated Leg Curl — Single Leg',
          videoUrl: 'https://www.youtube.com/watch?v=ELOCsoDSmrg',
          metric: 'weight_reps',
          targetReps: '8–12',
          targetSets: [2, 3, 3, 3, 1],
        },
        {
          id: 'bruegger',
          name: 'Bruegger Exercise',
          videoUrl: 'https://www.youtube.com/watch?v=KPT2KA0UK00',
          metric: 'band_reps',
          bandLabel: 'Cord color',
          targetReps: '4–8',
          targetSets: [2, 3, 3, 3, 1],
        },
        {
          id: 'pullover_extension',
          name: 'Pullover Extension w/ Dumbbells',
          videoUrl: 'https://www.youtube.com/watch?v=Cyqbmj7ePAk',
          metric: 'weight_reps',
          targetReps: '8–12',
          targetSets: [2, 3, 3, 3, 1],
        },
        {
          id: 'dead_bugs',
          name: 'Dead Bugs',
          videoUrl: 'https://www.youtube.com/watch?v=I5xbsA71v1A',
          metric: 'reps_only',
          targetReps: '8–15',
          targetSets: [2, 3, 3, 3, 1],
        },
        {
          id: 'hip_flexor_march',
          name: 'Hip Flexor March',
          videoUrl: 'https://www.youtube.com/watch?v=rA8V4jRP0l4',
          metric: 'band_reps',
          bandLabel: 'Band color',
          targetReps: '4–8',
          targetSets: [2, 3, 3, 3, 1],
        },
      ],
    },
  ],
};
